sudo: required
services:
  - docker


before_install:
  - docker build -t stevechung/docker-react -f Dockerfile.dev .

script:
  # -- --coverage to make sure to exit out of the test after it done.
  - docker run stevechung/docker-react npm run test -- --coverage 